In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
housing = pd.read_csv("../../datasets/Housing.csv")

In [3]:
housing.head(15)


price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0   13300000   7420         4          2        3      yes        no       no   
1   12250000   8960         4          4        4      yes        no       no   
2   12250000   9960         3          2        2      yes        no      yes   
3   12215000   7500         4          2        2      yes        no      yes   
4   11410000   7420         4          1        2      yes       yes      yes   
5   10850000   7500         3          3        1      yes        no      yes   
6   10150000   8580         4          3        4      yes        no       no   
7   10150000  16200         5          3        2      yes        no       no   
8    9870000   8100         4          1        2      yes       yes      yes   
9    9800000   5750         3          2        4      yes       yes       no   
10   9800000  13200         3          1        2      yes        no      yes   
11   9681000   6000         4          3        2      yes       yes      yes   
12   9310000   6550         4          2        2      yes        no       no   
13   9240000   3500         4          2        2      yes        no       no   
14   9240000   7800         3          2        2      yes        no       no   

   hotwaterheating airconditioning  parking prefarea furnishingstatus  
0               no             yes        2      yes        furnished  
1               no             yes        3       no        furnished  
2               no              no        2      yes   semi-furnished  
3               no             yes        3      yes        furnished  
4               no             yes        2       no        furnished  
5               no             yes        2      yes   semi-furnished  
6               no             yes        2      yes   semi-furnished  
7               no              no        0       no      unfurnished  
8               no             yes        2      yes        furnished  
9               no             yes        1      yes      unfurnished  
10              no             yes        2      yes        furnished  
11             yes              no        2       no   semi-furnished  
12              no             yes        1      yes   semi-furnished  
13             yes              no        2       no        furnished  
14              no              no        0      yes   semi-furnished

In [4]:
housing.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [5]:
dataset = (housing[0:10])[["area", "bedrooms", "stories", "price"]]

In [6]:
dataset

area  bedrooms  stories     price
0   7420         4        3  13300000
1   8960         4        4  12250000
2   9960         3        2  12250000
3   7500         4        2  12215000
4   7420         4        2  11410000
5   7500         3        1  10850000
6   8580         4        4  10150000
7  16200         5        2  10150000
8   8100         4        2   9870000
9   5750         3        4   9800000

In [7]:
model = linear_model.LinearRegression()
model.fit(dataset[["area", "bedrooms", "stories"]], dataset.price)

LinearRegression()

In [8]:
model.coef_

array([-1.14390465e+02,  2.55564926e+05, -1.17971731e+05])

In [9]:
model.intercept_

np.float64(11559738.055743875)

In [10]:
model.predict([[7420, 4, 3]])

c:\Ella-Liza\ing dev\ML-AI-Data Science\ml journey\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11379305.31595949])

In [11]:
model.predict([[2320, 2, 3]])

c:\Ella-Liza\ing dev\ML-AI-Data Science\ml journey\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11451566.8353659])

In [12]:
mylist = [5, 1, 2]
mylist.index(0)

ValueError: 0 is not in list

TypeError: list expected at most 1 argument, got 3

In [ ]:
class Solution:
    def twoSum(self, nums, target):
        for num in nums:
            for i in range((nums.index(num)) + 1, len(nums)):
                if (num + nums[i]) == target:
                    print(num, "+", nums[i], " = ", num+nums[i])
                    return [nums.index(num), i]
        

obj = Solution()
obj.twoSum([-1,-2,-3,-4,-5], -8)

-3 + -5  =  -8


[2, 4]

In [ ]:
-4 + -5 == -8

False

In [ ]:
mystr = "Hello"
mystr[::-1]

'olleH'

In [ ]:
class Solution:
    def isPalindrome

AttributeError: 'str' object has no attribute '__reversed__'